<?php
/**
 * @package gallery
 * @author Dark Ghost
 * @access public
 * @since 1.5.6 (19.03.12)
 * Подсказки по шаблонам для редактора в админ панели.
 * Tooltip for tag in templates for editor in admin panel.
 */


return array(
//no modify keys
    'main' => array(
        '{THEME}' => '{THEME}',
        '[aviable-gallery= ] [/aviable-gallery]' => '[aviable-gallery= ]',
        '[not-aviable-gallery= ] [/not-aviable-gallery]' => '[not-aviable-gallery= ]',
        '[group=] [/group]' => '[group=]',
        '[not-group=] [/not-group]' => '[not-group=]',
        '{include file="file.tpl"}' => '{include file=".tpl"}',
        '{speedbar}' => '{speedbar}',
        '{search_keyword}' => '{search_keyword} слово по которому проводится поиск.',
        '{alfa}' => '{alfa} - html разметка алфавита.',
        '{content}' => '{content} - скомпилированный контент.',
        '{pagination}' => '{pagination} - постраничная навигация.',
        '{cat_tree}' => '{cat_tree} - дерево категорий.'
    ),
    'cover' => array(
        '{THEME}' => '{THEME}',
        '[aviable-gallery= ] [/aviable-gallery]' => '[aviable-gallery= ]',
        '[not-aviable-gallery= ] [/not-aviable-gallery]' => '[not-aviable-gallery= ]',
        '[group=] [/group]' => '[group=]',
        '[not-group=] [/not-group]' => '[not-group=]',
        '{include file="file.tpl"}' => '{include file=".tpl"}',
        //-----
        '[access_granted] [/access_granted]' => '[access_granted]',
        '[access_denied] [/access_denied]' => '[access_denied]',
        '[category] [/category] ' => '[category] ',
        '[albom] [/albom]' => '[albom]',
        '[file] [/file]' => '[file]',
        '[link] [/link]' => '[link]',
        '[catlink] [/catlink]' => '[catlink] ',
        '{src}' => '{src}',
        '{name}' => '{name}',
        '{albom_num}' => '{albom_num}',
        '{file_num}' => '{file_num}',
        '{category}' => '{category}',
        '{width}x{height}' => '{width}x{height}',
        '{date}' => '{date}'
    ),
    'show_full' => array(
        '{THEME}' => '{THEME}',
        '[aviable-gallery= ] [/aviable-gallery]' => '[aviable-gallery= ]',
        '[not-aviable-gallery= ] [/not-aviable-gallery]' => '[not-aviable-gallery= ]',
        '[group=] [/group]' => '[group=]',
        '[not-group=] [/not-group]' => '[not-group=]',
        '{include file="file.tpl"}' => '{include file=".tpl"}',
        //---
        '[next-file][/next-file]' => '[next-file][/next-file]',
        '[prev-file][/prev-file]' => '[prev-file][/prev-file]',
        '[file-image][/file-image]' => '[file-image][/file-image]',
        '[file-video][/file-video]' => '[file-video][/file-video]',
        '{media= , }' => '{media=640,360}',
        '[field-label][/field-label]' => '[field-label][/field-label]',
        '{label}' => '{label}',
        '{file-path}' => '{file-path}',
        '{file-title}' => '{file-title}',
        '{title}' => '{title}',
        '[field-colors][/field-colors]' => '[field-colors][/field-colors]',
        '{colors}' => '{colors}',
        '{width}x{height}' => '{width}x{height}',
        '{size}' => '{size}',
        '{date}' => '{date}',
        '{blog_html}' => '{blog_html}',
        '{bb_code}' => '{bb_code}',
        '{tag}' => '{tag}',
        '[field-description] [/field-description]' => '[field-description] [/field-description]',
        '[edit-description] [/edit-description]' => '[edit-description] [/edit-description]',
        '{description}' => '{description}',
        '{author}' => '{author}- userinfo',
        '{foto}' => '{foto}- userinfo',
        '{email}' => '{email}- userinfo',
        '{pm}' => '{pm}- userinfo',
        '{fullname}' => '{fullname}- userinfo',
        '{status}' => '{status} - userinfo',
        '[time_limit][/time_limit]' => '[time_limit][/time_limit]- userinfo',
        '{time_limit}' => '{time_limit}- userinfo',
        '{comm_num}' => '{comm_num}- userinfo',
        '{last_comments}' => '{last_comments}- userinfo',
        '{registration}' => '{registration}- userinfo',
        '{lastdate}' => '{lastdate}- userinfo',
        '{land}' => '{land}- userinfo',
        '{info}' => '{info}- userinfo',
        '[addcommentfile][/addcommentfile]' => '[addcommentfile][/addcommentfile]',
        '{addcomments}' => '{addcomments}',
        '{info}' => ' {info}',
        '{comments}' => '{comments}',
        '{pagination}' => '{pagination}'
    ),
    'show_preview' => array(
        '{THEME}' => '{THEME} ',
        '[aviable-gallery= ] [/aviable-gallery]' => '[aviable-gallery= ]',
        '[not-aviable-gallery= ] [/not-aviable-gallery]' => '[not-aviable-gallery= ]',
        '[group=] [/group]' => '[group=]',
        '[not-group=] [/not-group]' => '[not-group=]',
        '{include file="file.tpl"}' => '{include file=".tpl"}',
        //---
        '[next-file][/next-file]' => '[next-file][/next-file]',
        '[prev-file][/prev-file]' => '[prev-file][/prev-file]',
        '[file-image][/file-image]' => '[file-image][/file-image]',
        '[file-video][/file-video]' => '[file-video][/file-video]',
        '{media= , }' => '{media=640,360}',
        '[field-label][/field-label]' => '[field-label][/field-label]',
        '{label}' => '{label}',
        '{file-path}' => '{file-path}',
        '{file-title}' => '{file-title}',
        '{title}' => '{title}',
        '[field-colors][/field-colors]' => '[field-colors][/field-colors]',
        '{colors}' => '{colors}',
        '{width}x{height}' => '{width}x{height}',
        '{size}' => '{size}',
        '{date}' => '{date}',
        '{blog_html}' => '{blog_html}',
        '{bb_code}' => '{bb_code}',
        '{tag}' => '{tag}',
        '[field-description] [/field-description]' => '[field-description] [/field-description]',
        '[edit-description] [/edit-description]' => '[edit-description] [/edit-description]',
        '{description}' => '{description}',
        '{author}' => '{author} - userinfo',
        '{foto}' => '{foto}- userinfo',
        '{email}' => '{email}- userinfo',
        '{pm}' => '{pm}- userinfo',
        '{fullname}' => '{fullname}- userinfo',
        '{status}' => '{status} - userinfo',
        '[time_limit][/time_limit]' => '[time_limit][/time_limit]- userinfo',
        '{time_limit}' => '{time_limit}- userinfo',
        '{comm_num}' => '{comm_num}- userinfo',
        '{last_comments}' => '{last_comments}- userinfo',
        '{registration}' => '{registration}- userinfo',
        '{lastdate}' => '{lastdate}- userinfo',
        '{land}' => '{land}- userinfo',
        '{info}' => '{info}- userinfo',
        '[addcommentfile][/addcommentfile]' => '[addcommentfile][/addcommentfile]',
        '{addcomments}' => '{addcomments}',
        '{info}' => ' {info}',
        '{comments}' => '{comments}',
        '{pagination}' => '{pagination}'
    ),
    'addcomments' => array(
        '{THEME}' => '{THEME}',
        '[aviable-gallery= ] [/aviable-gallery]' => '[aviable-gallery= ]',
        '[not-aviable-gallery= ] [/not-aviable-gallery]' => '[not-aviable-gallery= ]',
        '[group=] [/group]' => '[group=]',
        '[not-group=] [/not-group]' => '[not-group=]',
        '{include file="file.tpl"}' => '{include file=".tpl"}',
        //--
        '[not-logged][/not-logged]' => '[not-logged][/not-logged]',
        '{editor}' => '{editor}',
        '[sec_code][/sec_code]' => '[sec_code][/sec_code]',
        '{sec_code}' => '{sec_code}',
        '[recaptcha][/recaptcha]' => '[recaptcha][/recaptcha]',
        '{recaptcha}' => '{recaptcha}'
    ),
    'comments' => array(
        '{THEME}' => '{THEME}',
        '[aviable-gallery= ] [/aviable-gallery]' => '[aviable-gallery= ]',
        '[not-aviable-gallery= ] [/not-aviable-gallery]' => '[not-aviable-gallery= ]',
        '[group=] [/group]' => '[group=]',
        '[not-group=] [/not-group]' => '[not-group=]',
        '{include file="file.tpl"}' => '{include file=".tpl"}',
        //--
        '{foto}' => '{foto}',
        '[fast][/fast]' => '[fast][/fast]',
        '{author}' => '{author}',
        '{date}' => '{date}',
        '{group-name}' => '{group-name}',
        '{comment-id}' => '{comment-id}',
        '{mass-action}' => '{mass-action}',
        '[com-edit][/com-edit]' => '[com-edit][/com-edit]',
        '[com-del][/com-del]' => '[com-del][/com-del]',
        '{registration}' => '{registration}',
        '{comm-num}' => '{comm-num}',
        '{comment}' => '{comment}',
        '[signature][/signature]' => '[signature][/signature]',
        '{signature}' => '{signature}'
    ),
    'user_mode1' => array(
        '{THEME}' => '{THEME}',
        '[aviable-gallery= ] [/aviable-gallery]' => '[aviable-gallery= ]',
        '[not-aviable-gallery= ] [/not-aviable-gallery]' => '[not-aviable-gallery= ]',
        '[group=] [/group]' => '[group=]',
        '[not-group=] [/not-group]' => '[not-group=]',
        '{include file="file.tpl"}' => '{include file=".tpl"}',
        //--
        '[list-albom][/list-albom]' => '[list-albom][/list-albom]',
        '[link][/link]' => '[link][/link]',
        '{cover}' => '{cover}',
        '{title}' => '{title}',
        '[edit-link][/edit-link]' => '[edit-link][/edit-link]',
        '{albom}' => '{albom}',
        '[file-list][/file-list]' => '[file-list][/file-list]',
        '{id-file}' => '{id-file}',
        '{name}' => '{name}',
        '{preview-path}' => '{preview-path}',
    ),
    'user_mode2' => array(
        '{THEME}' => '{THEME}',
        '[aviable-gallery= ] [/aviable-gallery]' => '[aviable-gallery= ]',
        '[not-aviable-gallery= ] [/not-aviable-gallery]' => '[not-aviable-gallery= ]',
        '[group=] [/group]' => '[group=]',
        '[not-group=] [/not-group]' => '[not-group=]',
        '{include file="file.tpl"}' => '{include file=".tpl"}',
        //--
        '{add-form}' => '{add-form}',
        '{categoryes}' => '{categoryes}',
        '[file-list]' => '[file-list]',
        '{id-file}' => '{id-file}',
        '{name}' => '{name}',
        '{preview-path}' => '{preview-path}',
        '{total-file}' => '{total-file}'
    ),
    'albom_edit' => array(
        '{THEME}' => '{THEME}',
        '[aviable-gallery= ] [/aviable-gallery]' => '[aviable-gallery= ]',
        '[not-aviable-gallery= ] [/not-aviable-gallery]' => '[not-aviable-gallery= ]',
        '[group=] [/group]' => '[group=]',
        '[not-group=] [/not-group]' => '[not-group=]',
        '{include file="file.tpl"}' => '{include file=".tpl"}',
        //--
        '{files}' => '{files}',
        '[youtube][/youtube]' => '[youtube][/youtube]',
        '{form-access}' => '{form-access}',
        '{form-edit}' => '{form-edit}'
    ),

);
